- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: Praveen-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter tRAINER Name
    private:false
  tasks:
  - name: variable at task level
    vars:
      NAME: Praveen-task
    ansible.builtin.debug:
      msg: "Trainer name is : {{NAME}}"