- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exisits or not
    # when you want to run linux command directly i.e. in the case ansible module not available
    # when the user does not exisits, ansible treating this failure and comes out by default
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: output # output is variable name
    ignore_errors: true
  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"