- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exisits or not
    # when you want to run linux command directly i.e. in the case ansible module not available
    ansible.builtin.command: id roboshop
    register: output # output is variable name
  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"