- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    # list of map 
    loop:
    - {name: 'postfix', state: 'absent'}
    - {name: 'cyrus-sasl-plain', state: 'Installed'}
    - {name: 'mailx', state: 'absent'}
  